[book]
authors = ["Seb Blair"]
title = "Computer Architecture and Operating Systems"
language = "en"
multilingual = false
src = "content"

[preprocessor.pagetoc]
[output.html]
mathjax-support = true
git-repository-url = "https://github.com/uniofgreenwich/COMP1712_Exercises"
edit-url-template = "https://github.com/uniofgreenwich/COMP1712_Exercises/edit/main/{path}"
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]

[output.html.print]
enable = false 

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 4